services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: incentive
      POSTGRES_PASSWORD: incentive
      POSTGRES_DB: incentive_calc
    volumes:
      - incentive_pg_data:/var/lib/postgresql/data

volumes:
  incentive_pg_data:
